worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    
    upstream app_servers {
        server app1:80 max_fails=1 fail_timeout=5s;
        server app2:80 max_fails=1 fail_timeout=5s;
        server app3:80 max_fails=1 fail_timeout=5s;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Automatically retry if container is currently restarting
            proxy_next_upstream error timeout invalid_header http_502 http_503 http_504;
        }

        location /api/ {
            rewrite ^/api/(.*)$ /$1 break;
            
            proxy_pass http://backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
